INSERT INTO `auth_item` (`name`, `type`, `description`, `rule_name`, `data`, `created_at`, `updated_at`) VALUES
('create-cashvoucher', 1, 'Allow this user to create a cash voucher request', NULL, NULL, NULL, NULL),
('create-jobacc', 1, 'Allow this user to create a job accomplishment request', NULL, NULL, NULL, NULL),
('create-leave', 1, 'Allow this user to create a leave request', NULL, NULL, NULL, NULL),
('create-officialbusiness', 1, 'Allow this user to create an official business request', NULL, NULL, NULL, NULL),
('create-overtime', 1, 'Allow this user to create an overtime request', NULL, NULL, NULL, NULL),
('delete-cashvoucher', 1, 'Allow this user to delete a cash voucher request', NULL, NULL, NULL, NULL),
('delete-jobacc', 1, 'Allow this user to delete a job accomplishment request', NULL, NULL, NULL, NULL),
('delete-leave', 1, 'Allow this user to delete a leave request', NULL, NULL, NULL, NULL),
('delete-officialbusiness', 1, 'Allow this user to delete an official business request', NULL, NULL, NULL, NULL),
('delete-overtime', 1, 'Allow this user to delete an overtime request', NULL, NULL, NULL, NULL),
('update-cashvoucher', 1, 'Allow this user to update a cash voucher request', NULL, NULL, NULL, NULL),
('update-jobacc', 1, 'Allow this user to update a job accomplishment request', NULL, NULL, NULL, NULL),
('update-leave', 1, 'Allow this user to update a leave request', NULL, NULL, NULL, NULL),
('update-officialbusiness', 1, 'Allow this user to update an official business request', NULL, NULL, NULL, NULL),
('update-overtime', 1, 'Allow this user to update an overtime request', NULL, NULL, NULL, NULL),
('view-cashvoucher', 1, 'Allow this user to view all filed cash voucher request', NULL, NULL, NULL, NULL),
('view-jobacc', 1, 'Allow this user to view all filed job accomplishment request', NULL, NULL, NULL, NULL),
('view-leave', 1, 'Allow this user to view all filed leave request', NULL, NULL, NULL, NULL),
('view-officialbusiness', 1, 'Allow this user to view all filed official business request', NULL, NULL, NULL, NULL),
('view-overtime', 1, 'Allow this user to view all filed overtime request', NULL, NULL, NULL, NULL);